[project]
name = "griptape_nodes_lora_training_library"
version = "0.1.0"
description = "Template for Users to create Custom Libraries and Nodes"
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "huggingface-hub>=1.0.1,<2",
]

[tool.uv.sources]
griptape-nodes-engine = { git = "https://github.com/griptape-ai/griptape-nodes-engine", rev="latest"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
