[project]
name = "griptape_nodes_lora_training_library"
version = "0.64.0"
description = "Template for Users to create Custom Libraries and Nodes"
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "huggingface-hub>=1.0.1,<2",
]

[tool.uv.sources]
griptape-nodes-engine = { git = "https://github.com/griptape-ai/griptape-nodes-engine", rev="latest"}

[dependency-groups]
dev = ["pyright>=1.1.396", "pytest-asyncio>=0.21.0", "ruff>=0.8.0", "pytest", "griptape-nodes-engine"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
